# Generated by Django 5.0.6 on 2024-06-27 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('empfname', models.CharField(max_length=64)),
                ('emplname', models.CharField(max_length=64)),
                ('emppasswd', models.CharField(max_length=256)),
                ('emprole', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='薬剤 ID')),
                ('medicinename', models.CharField(max_length=64, verbose_name='薬剤名')),
                ('unit', models.CharField(max_length=8, verbose_name='単位')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='患者 ID')),
                ('patfname', models.CharField(max_length=64, verbose_name='患者名')),
                ('patlname', models.CharField(max_length=64, verbose_name='患者姓')),
                ('hokenmei', models.CharField(max_length=64, verbose_name='保険証名記号番号')),
                ('hokenexp', models.DateField(verbose_name='有効期限')),
            ],
        ),
        migrations.CreateModel(
            name='Tabyouin',
            fields=[
                ('tabyouinid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='他病院ID')),
                ('tabyouinmei', models.CharField(max_length=64, verbose_name='他病院名')),
                ('tabyouinaddress', models.CharField(max_length=64, verbose_name='他病院住所')),
                ('tabyouintel', models.CharField(max_length=13, verbose_name='他病院電話番号')),
                ('tabyouinshihonkin', models.IntegerField(verbose_name='資本金')),
                ('kyukyu', models.IntegerField(help_text='救急対応の時は1、そうでない時は1以外', verbose_name='救急フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('medicine_name', models.CharField(default='unknown', max_length=100, verbose_name='薬剤名')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okanaga.medicine', verbose_name='薬剤')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okanaga.patient', verbose_name='患者')),
            ],
        ),
    ]
