# Generated by Django 5.0.6 on 2024-07-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okanaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabyouin',
            name='tabyouintel',
            field=models.CharField(max_length=20, verbose_name='他病院電話番号'),
        ),
    ]
