# Generated by Django 5.0.6 on 2024-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okanaga', '0003_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='shiiretel',
            field=models.CharField(max_length=15, verbose_name='仕入れ先電話番号'),
        ),
    ]
